services:
    database:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        ports:
            - 3306:3306
