services:
    database:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 3
    server:
        build:
            context: .
        depends_on:
            database:
                condition: service_healthy
        environment:
            NODE_ENV: production
            DATABASE_HOST: database
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_PORT: ${DATABASE_PORT}
            PORT: ${PORT}
            JWT_SECRET: ${JWT_SECRET}
            JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
            MAIL_APIKEY: ${MAIL_APIKEY}
        ports:
            - 3000:3000
